[workspace]
authors = ["Mads-Peter <machri@phys.au.dk>"]
channels = ["conda-forge"]
name = "structure_biology"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
quarto = ">=1.8.27,<2"
