[workspace]
authors = ["Mads-Peter <machri@phys.au.dk>"]
channels = ["conda-forge", "anaconda"]
name = "structure_biology"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pyqt = ">=5.15.11,<6"
python = "3.12.*"
pymol-open-source = ">=3"
quarto = ">=1.8.27,<2"
