website:
  title: "Strukturbiologi TØ"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: exercises/index.qmd
        text: Øvelser
        icon: pencil
      - href: other_notes/guides.qmd
        text: Guides
        icon: book
      - href: videos/index.qmd
        text: Videoer
        icon: youtube
      - href: exam_sets/index.qmd
        text: Eksamenssæt
        icon: file-earmark-text

  sidebar:
    - id: exercises-sidebar
      style: "docked"
      contents: exercises

    - id: pymol-sidebar
      style: "docked"
      title: "Guides"
      contents:
          - other_notes/installation_pixi.qmd
          - other_notes/installation_pymol.qmd
          - other_notes/installation_vscode.qmd
          - other_notes/pymol_guide_1.qmd
          - other_notes/pymol_guide_2.qmd
          - other_notes/pymol_learning_path.qmd

    - id: videor-sidebar
      style: "docked"
      contents: videos

    - id: exam_sets-sidebar
      style: "docked"
      contents: exam_sets


filters:
  - callout-solution
  - collapse-callouts

format:
  html:
    toc: true
    number-sections: true
    css: config/quarto/styling/styles.css
    theme:
      light: cosmo
      dark: [darkly, config/quarto/styling/theme-dark.scss]
    respect-user-color-scheme: true

format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf
  - format: docx
    text: Word
    icon: file-word




teaching:
  show-solutions: false
  default-solution-title: "Svar"
  collapse-tips: true
