---
title: Installation
---

## Pixi

Denne installationsvejledning er baseret på <https://munch-group.org/bioinformatics/chapters/python/appendix_bsf.html>

Start med at installere pixi:

**Mac:**

1.  Kopier kommandoen nedenfor.

2.  Åbn din Terminal-applikation.

3.  Indsæt kommandoen i Terminalvinduet, og tryk på Enter. Du vil blive bedt om at angive enten din brugeradgangskode eller tilladelser til de installerede apps flere gange.

```sh
curl -fsSL https://pixi.sh/install.sh | sh
```
**Windows:**

1.  Kopier kommandoen nedenfor

2.  Åbn din PowerShell-applikation.

3.  Indsæt kommandoen i PowerShell-vinduet, og tryk på Enter. Du vil blive bedt flere gange om at tillade appen at foretage ændringer på din computer.

```sh
powershell -ExecutionPolicy ByPass -c "irm -useb https://pixi.sh/install.ps1 | iex"
```

Hvis det ikke virker, så kan du [downloade denne interaktive installer](https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-pc-windows-msvc.msi) og køre den.

## PyMOL 3

**Mac:**

1.  Opret en mappe på din computer dedikeret til BMSF-kurset. Lad os sige, at du kalder den `BMSF` og lægger den i din mappe `Dokumenter`.

2.  Åbn din Terminal-applikation, og naviger til den mappe ved hjælp af cd (noget i retning af cd Dokumenter og derefter cd BMSF).

3.  Når du er i mappen 'BMSF', skal du indsætte kommandoen i Terminalvinduet og trykke på Enter. Du vil blive bedt om at angive enten din brugeradgangskode eller tilladelser til de installerede apps flere gange.

```sh
pixi init --platform osx-64 -c conda-forge -c anaconda -c schrodinger && pixi config set --local run-post-link-scripts insecure && pixi add pyqt "pymol-bundle=3.1" "vtk-m=1.8"
```
**Windows:**

1.  Opret en mappe på din computer dedikeret til BMSF-kurset. Lad os sige, at du kalder den `BMSF` og lægger den i din mappe `Dokumenter`.

2.  Åbn din PowerShell-applikation, og naviger til den mappe ved hjælp af cd (noget i retning af cd Dokumenter og derefter cd BMSF).

3.  Når du er i mappen 'BMSF', skal du indsætte kommandoen i PowerShell-vinduet og trykke på Enter. Du vil blive bedt flere gange om at tillade appen at foretage ændringer på din computer.

```sh
pixi init -c conda-forge -c anaconda -c schrodinger ; pixi config set --local run-post-link-scripts insecure ; pixi add pyqt "pymol-bundle=3.1" "vtk-m=1.8"
```
For at køre PyMOL i din BMSF-mappe skal du bruge denne kommando:

```sh
pixi run pymol
```

PyMOL 3 burde nu åbne og præsentere dig for en dialogboks, der beder dig om at aktivere det ved hjælp af en licens.

Du kan hente licensen til PyMOL under Materialer/PyMOL på Brightspace.

Gem licensen på din computer.

Åben den fra PyMOL dialogboks.

Hurra, du er igang.

## VS Code

Til redigering af scripts skal du bruge en plain text-editor. Det er ikke godt at bruge Word eller andre tekstbehandlingsprogrammer, da de har svært ved at undlade at indsætte koder i teksten. På samme måde som på Bioinformatik-kurset benytter vi Microsoft VS Code, der er en fremragende teksteditor, der fås til både Windows, Mac og Linux:

**<https://code.visualstudio.com/download>**



