project:
  type: website
  output-dir: _site
  resources:
    - files/

metadata-files:
  - config/quarto/website.yml
  - scheduled-docs_files/draft-list.yml

profile:
  group:
    - [exercise, solution]

website:
  draft-mode: gone

teaching:
  show-solutions: false
