# Profile active when rendering student handouts
project:
  output-dir: _site

website:
  navbar:
    right:
      - href: solution/index.html
        text: Go to solution version
        icon: book-fill

format:
  typst:
    number-sections: true
    number-depth: 3
    toc: true
    toc-depth: 2
    margin: {left: 2cm, right: 2cm, top: 2.5cm, bottom: 2.5cm}
    text: PDF
    icon: file-pdf
  docx: default

teaching:
  show-solutions: false
