# Profile active when rendering exercise handouts
project:
  output-dir: _site

website:
  navbar:
    right:
      - href: instructor/index.html
        text: Go to solution version
        icon: book-fill

teaching:
  show-solutions: false